import type { ToolDefinition } from './definition'

export const TOOL_CATALOG: readonly ToolDefinition[] = [
    {
        id: 'select',
        label: 'Select',
        shortcut: 'm',
        geometry: 'select.rect',
        ink: 'source-over',
        stamp: 'none',
        trace: 'preview',
    },
    {
        id: 'selectEllipse',
        label: 'Select ellipse',
        shortcut: 'm',
        geometry: 'select.ellipse',
        ink: 'source-over',
        stamp: 'none',
        trace: 'preview',
    },
    {
        id: 'lasso',
        label: 'Lasso',
        shortcut: 'q',
        geometry: 'select.lasso',
        ink: 'source-over',
        stamp: 'none',
        trace: 'preview',
    },
    {
        id: 'wand',
        label: 'Magic wand',
        shortcut: 'w',
        geometry: 'select.wand',
        ink: 'source-over',
        stamp: 'none',
        trace: 'preview',
    },
    {
        id: 'eyedropper',
        label: 'Eyedropper',
        shortcut: 'i',
        geometry: 'sample',
        ink: 'source-over',
        stamp: 'none',
        trace: 'preview',
    },
    {
        id: 'pencil',
        label: 'Pencil',
        shortcut: 'b',
        geometry: 'freehand',
        ink: 'source-over',
        stamp: 'brush',
        trace: 'direct',
    },
    {
        id: 'eraser',
        label: 'Eraser',
        shortcut: 'e',
        geometry: 'freehand',
        ink: 'erase',
        stamp: 'brush',
        trace: 'direct',
    },
    {
        id: 'line',
        label: 'Line',
        shortcut: 'l',
        geometry: 'line',
        ink: 'source-over',
        stamp: 'brush',
        trace: 'preview',
    },
    {
        id: 'rect',
        label: 'Rect',
        shortcut: 'u',
        geometry: 'rect',
        ink: 'source-over',
        stamp: 'brush',
        trace: 'preview',
    },
    {
        id: 'ellipse',
        label: 'Ellipse',
        shortcut: 'u',
        geometry: 'ellipse',
        ink: 'source-over',
        stamp: 'brush',
        trace: 'preview',
    },
    {
        id: 'bucket',
        label: 'Bucket',
        shortcut: 'g',
        geometry: 'flood',
        ink: 'source-over',
        stamp: 'none',
        trace: 'direct',
    },
]

export function toolBadge(definition: ToolDefinition): string {
    return definition.shortcut.toUpperCase()
}
